---
- name: Deploy Grafana
  hosts: localhost
  gather_facts: false
  vars:
    deploy_local: false
  roles:
    - common
    - prepare
    - operator
    - grafana
    - datasource
    - dashboard
  tasks:
    - name: Show deployment summary
      ansible.builtin.pause:
        seconds: 0
        prompt: |
          {{ lookup('ansible.builtin.template', 'roles/grafana/templates/summary.j2') }}
