---
openshift_monitoring_namespace: openshift-monitoring
grafana_namespace: perfscale
local_grafana_fqdn: ""
prometheus_route: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
star_dashboards: true
deploy_local: false
container_engine: podman
prom_dir: .prometheus
