---
- name: Create '{{ grafana_namespace }}' namespace
  ansible.builtin.command:
    cmd: oc apply -f -
    stdin: "{{ lookup('template', 'namespace.j2') }}"

- name: Define the operatorGroup for OLM
  ansible.builtin.command:
    cmd: oc apply -f -
    stdin: "{{ lookup('template', 'operatorgroup.j2') }}"

- name: Add subscription for OLM management of the grafana operator
  ansible.builtin.command:
    cmd: oc apply -f -
    stdin: "{{ lookup('template', 'subscription.j2') }}"
